# Generated by Django 5.2.17 on 2026-09-30 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('starts_at', models.DateTimeField(unique=True)),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('is_open', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_survey_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SurveyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(editable=False, max_length=24, unique=True)),
                ('customer_name', models.CharField(max_length=160)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=40)),
                ('site_address_line1', models.CharField(max_length=255)),
                ('site_address_line2', models.CharField(blank=True, max_length=255)),
                ('site_area', models.CharField(blank=True, max_length=120)),
                ('site_city', models.CharField(max_length=120)),
                ('needs_description', models.TextField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=12)),
                ('internal_notes', models.TextField(blank=True)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('guest_link_nonce', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_bookings', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='surveys.surveyslot')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='surveyslot',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='survey_slot_positive_capacity'),
        ),
        migrations.AddConstraint(
            model_name='surveyslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='survey_slot_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='surveybooking',
            index=models.Index(fields=['slot', 'status'], name='surveys_sur_slot_id_91a4a4_idx'),
        ),
    ]
