# Generated by Django 5.2.17 on 2026-09-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
