# Generated by Django 5.2.17 on 2026-09-24 11:23

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('full_description', models.TextField()),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('warranty_text', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('regular_price__gte', 0)), name='product_regular_price_gte_0'), models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), models.Q(('sale_price__gte', 0), ('sale_price__lt', models.F('regular_price'))), _connector='OR'), name='product_valid_sale_price'), models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='product_stock_quantity_gte_0'), models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), name='product_sku_ci_unique'), models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='product_slug_ci_unique')],
            },
        ),
    ]
