# Generated by Django 5.2.17 on 2026-09-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('integer_value', models.BigIntegerField(blank=True, null=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ['definition__sort_order', 'definition__label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(max_length=120)),
                ('label', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120)),
                ('label', models.CharField(max_length=120)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('choice', 'Choice')], max_length=10)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_displayed', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'category'], name='catalog_pro_is_publ_cba3a6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'brand'], name='catalog_pro_is_publ_1777b2_idx'),
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_values', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='catalog.specificationchoice'),
        ),
        migrations.AddField(
            model_name='specificationdefinition',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specification_definitions', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='specificationchoice',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='catalog.specificationdefinition'),
        ),
        migrations.AddField(
            model_name='productspecificationvalue',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_values', to='catalog.specificationdefinition'),
        ),
        migrations.AddConstraint(
            model_name='specificationdefinition',
            constraint=models.UniqueConstraint(fields=('category', 'key'), name='spec_definition_category_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='specificationchoice',
            constraint=models.UniqueConstraint(fields=('definition', 'value'), name='spec_choice_definition_value_unique'),
        ),
        migrations.AddConstraint(
            model_name='productspecificationvalue',
            constraint=models.UniqueConstraint(fields=('product', 'definition'), name='product_spec_value_unique'),
        ),
        migrations.AddConstraint(
            model_name='productspecificationvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('text_value__isnull', False), ('integer_value__isnull', True), ('decimal_value__isnull', True), ('boolean_value__isnull', True), ('choice__isnull', True)), models.Q(('text_value__isnull', True), ('integer_value__isnull', False), ('decimal_value__isnull', True), ('boolean_value__isnull', True), ('choice__isnull', True)), models.Q(('text_value__isnull', True), ('integer_value__isnull', True), ('decimal_value__isnull', False), ('boolean_value__isnull', True), ('choice__isnull', True)), models.Q(('text_value__isnull', True), ('integer_value__isnull', True), ('decimal_value__isnull', True), ('boolean_value__isnull', False), ('choice__isnull', True)), models.Q(('text_value__isnull', True), ('integer_value__isnull', True), ('decimal_value__isnull', True), ('boolean_value__isnull', True), ('choice__isnull', False)), _connector='OR'), name='product_spec_exactly_one_value'),
        ),
    ]
