# Generated by Django 5.2.17 on 2026-09-27 15:29

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.IntegerField()),
                ('previous_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('manual_adjustment', 'Manual adjustment'), ('order_placed', 'Order placed'), ('order_cancelled', 'Order cancelled')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', '-created_at', '-id'], name='catalog_inv_product_3fb3a4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='inventory_delta_nonzero'), models.CheckConstraint(condition=models.Q(('new_quantity', django.db.models.expressions.CombinedExpression(models.F('previous_quantity'), '+', models.F('quantity_delta')))), name='inventory_movement_balanced')],
            },
        ),
    ]
