# Generated by Django 5.2.17 on 2026-09-30 10:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_inventorymovement_order'),
        ('orders', '0002_order_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.UniqueConstraint(condition=models.Q(('reason', 'order_cancelled')), fields=('order', 'product'), name='one_cancellation_restock_per_product'),
        ),
    ]
