# Generated by Django 5.2.17 on 2026-10-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_inventorymovement_one_cancellation_restock_per_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brands/'),
        ),
    ]
