# Generated by Django 5.2.17 on 2026-09-27 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ORDER_PLACED', 'Order placed'), ('ORDER_STATUS_CHANGED', 'Order status changed'), ('SURVEY_CONFIRMED', 'Survey confirmed'), ('SURVEY_CHANGED', 'Survey changed'), ('SURVEY_CANCELLED', 'Survey cancelled'), ('PASSWORD_RESET', 'Password reset')], max_length=32)),
                ('recipient', models.EmailField(max_length=254)),
                ('template_name', models.CharField(max_length=100)),
                ('context', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('claim_token', models.UUIDField(blank=True, default=None, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at', 'id'], name='communicati_status_dc1a0c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='email_attempts_nonnegative')],
            },
        ),
    ]
