# Generated by Django 5.2.17 on 2026-09-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_emailoutbox_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailoutbox',
            name='event_type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order placed'), ('ORDER_STATUS_CHANGED', 'Order status changed'), ('ORDER_CANCELLED', 'Order cancelled'), ('SURVEY_CONFIRMED', 'Survey confirmed'), ('SURVEY_CHANGED', 'Survey changed'), ('SURVEY_CANCELLED', 'Survey cancelled'), ('PASSWORD_RESET', 'Password reset')], max_length=32),
        ),
    ]
