# Generated by Django 5.2.17 on 2026-09-30 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_alter_emailoutbox_event_type'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailoutbox',
            name='survey_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_events', to='surveys.surveybooking'),
        ),
    ]
